import React from 'react';
import { ShieldCheck, X, AlertOctagon, UserCheck, Lock, Clock, FileEdit } from 'lucide-react';

interface PrivacyNoticeModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export const PrivacyNoticeModal: React.FC<PrivacyNoticeModalProps> = ({ isOpen, onClose }) => {
  if (!isOpen) return null;

  return (
    <div id="privacy-modal-overlay" className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-900/60 backdrop-blur-xs animate-in fade-in duration-200">
      <div 
        id="privacy-modal-card" 
        className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-y-auto shadow-2xl border border-slate-200 flex flex-col"
      >
        <div className="flex items-center justify-between p-6 border-b border-slate-100 sticky top-0 bg-white/95 backdrop-blur-xs z-10">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-blue-50 border border-blue-100 flex items-center justify-center text-blue-600">
              <ShieldCheck className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-slate-900">Academic Data Privacy & Responsible AI Charter</h2>
              <p className="text-xs text-slate-500">FERPA Compliant & Ethical Machine Learning Framework</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-lg hover:bg-slate-100 text-slate-400 hover:text-slate-600 flex items-center justify-center transition-colors"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <div className="p-6 space-y-6 text-sm text-slate-600 leading-relaxed">
          {/* Advisory Notice Banner */}
          <div className="p-4 rounded-xl bg-amber-50 border border-amber-200 flex items-start gap-3">
            <AlertOctagon className="w-5 h-5 text-amber-700 shrink-0 mt-0.5" />
            <div>
              <h4 className="text-xs font-bold text-amber-900 uppercase tracking-wide">Human-in-the-Loop Mandate</h4>
              <p className="text-xs text-amber-800 mt-1">
                Statistical predictions and risk badges generated by this system are advisory algorithmic estimates. They must <strong>never</strong> be used as punitive or automated disciplinary measures. Faculty and mentors must exercise holistic academic judgment.
              </p>
            </div>
          </div>

          {/* Section 1 */}
          <div>
            <h3 className="text-sm font-semibold text-slate-900 flex items-center gap-2 mb-2">
              <Lock className="w-4 h-4 text-blue-600" />
              1. What Data Is Collected & Why
            </h3>
            <p className="text-xs text-slate-600">
              The system collects academic engagement metrics strictly pertinent to course completion: attendance rates, internal assessment scores, assignment timeliness, LMS platform activity, and cumulative GPA. This information is processed exclusively to deliver early-intervention academic support and personalized learning strategies.
            </p>
          </div>

          {/* Section 2 */}
          <div>
            <h3 className="text-sm font-semibold text-slate-900 flex items-center gap-2 mb-2">
              <UserCheck className="w-4 h-4 text-indigo-600" />
              2. Access Control & Strict Data Isolation
            </h3>
            <p className="text-xs text-slate-600">
              Students have authenticated access strictly to their own personal academic records, explanations, and action plans. Cross-student data exposure is strictly prohibited by role-based authorization tokens. Faculty members can access only students enrolled in their respective departments.
            </p>
          </div>

          {/* Section 3 */}
          <div>
            <h3 className="text-sm font-semibold text-slate-900 flex items-center gap-2 mb-2">
              <Clock className="w-4 h-4 text-slate-700" />
              3. Data Retention Period
            </h3>
            <p className="text-xs text-slate-600">
              Academic records and model predictions are retained for the duration of the student's active degree program plus two academic years for longitudinal accreditation analysis, after which student identifiers are anonymized.
            </p>
          </div>

          {/* Section 4 */}
          <div>
            <h3 className="text-sm font-semibold text-slate-900 flex items-center gap-2 mb-2">
              <FileEdit className="w-4 h-4 text-emerald-600" />
              4. Right to Audit & Correction
            </h3>
            <p className="text-xs text-slate-600">
              Students and advisors may request manual verification or correction of any erroneous academic record (such as excused medical absences or revised grading rubrics) by submitting an appeal to the Department Head or Academic Registrar.
            </p>
          </div>
        </div>

        <div className="p-4 border-t border-slate-100 bg-slate-50 flex items-center justify-end rounded-b-2xl">
          <button
            onClick={onClose}
            className="px-4 py-2 bg-slate-900 text-white rounded-lg text-xs font-semibold hover:bg-slate-800 transition-colors"
          >
            I Understand & Acknowledge
          </button>
        </div>
      </div>
    </div>
  );
};
